import getEnvSafely from '@/utils/env/utils';

const STRIPE_API_KEY = getEnvSafely('STRIPE_API_KEY');
const OPENAI_API_KEY = getEnvSafely('OPENAI_API_KEY');
const CLERK_SECRET_KEY = getEnvSafely('CLERK_SECRET_KEY');
const REPLICATE_API_TOKEN = getEnvSafely('REPLICATE_API_TOKEN');
const STRIPE_WEBHOOK_SECRET = getEnvSafely('STRIPE_WEBHOOK_SECRET');
const RIFFUSION_API_KEY = getEnvSafely('RIFFUSION_API');
const ZEROSCOPE_API = getEnvSafely('ZEROSCOPE_API');
const RIFFUSSION_USER_NAME = getEnvSafely('RIFFUSSION_USER_NAME');
const RIFFUSION_TOKEN = getEnvSafely('RIFFUSION_TOKEN');
const RIFFUSION_API_NAME = getEnvSafely('RIFFUSION_API_NAME');
const ZEROSCOPE_API_NAME = getEnvSafely('ZEROSCOPE_API_NAME');
const ZEROZCOPE_VERSION = getEnvSafely('ZEROZCOPE_VERSION');
const ZEROSCOPE_TOKEN = getEnvSafely('ZEROSCOPE_TOKEN');

const env = {
  STRIPE_API_KEY,
  OPENAI_API_KEY,
  CLERK_SECRET_KEY,
  REPLICATE_API_TOKEN,
  STRIPE_WEBHOOK_SECRET,
  RIFFUSION_API_KEY,
  ZEROSCOPE_API,
  RIFFUSSION_USER_NAME,
  RIFFUSION_TOKEN,
  RIFFUSION_API_NAME,
  ZEROSCOPE_API_NAME,
  ZEROZCOPE_VERSION,
  ZEROSCOPE_TOKEN,
};

export default env;
